#include<iostream>
#include<exception>
using namespace std;
int main()
{
	int a=10;
	int b=0;
	int c=a/b;
	cout<<"this is value"<<c<<endl;
}
